export const showData = [
  [
    {
      label: "占位",
      componentKey: 1,
      componentName: "other-block",
      api: "",
      method: "get",
      dataKey: "",
      col: 1,
      height: 250,
      previewImage: "https://i.loli.net/2019/03/11/5c8663be38f28.png",
    },
    {
      label: "占位",
      componentKey: 2,
      componentName: "other-block",
      api: "",
      method: "get",
      dataKey: "",
      col: 2,
      height: 250,
      previewImage: "https://i.loli.net/2019/03/11/5c8663be37781.png",
    },
    {
      label: "占位",
      componentKey: 3,
      componentName: "other-block",
      api: "",
      method: "get",
      dataKey: "",
      col: 3,
      height: 250,
      previewImage: "https://i.loli.net/2019/03/11/5c8663be3c255.png",
    },
    {
      label: "占位",
      componentKey: 4,
      componentName: "other-block",
      api: "",
      method: "get",
      dataKey: "",
      col: 4,
      height: 250,
      previewImage: "https://i.loli.net/2019/03/11/5c8664d04e3e7.png",
    },
    {
      label: "邮件营销",
      componentKey: 5,
      componentName: "text-text",
      api: "/report/getCountData",
      method: "get",
      dataKey: "countKey",
      col: 4.8,
      height: 100,
      previewImage: "https://i.loli.net/2019/03/11/5c8663be3a93d.png",
    },
    {
      label: "联盟广告",
      componentKey: 6,
      componentName: "text-text",
      api: "/report/getCountData",
      method: "get",
      dataKey: "countKey",
      col: 4.8,
      height: 100,
      previewImage: "https://i.loli.net/2019/03/11/5c8663be31676.png",
    },
    {
      label: "视频广告",
      componentKey: 7,
      componentName: "text-text",
      api: "/report/getCountData",
      method: "get",
      dataKey: "countKey",
      col: 4.8,
      height: 100,
      previewImage: "https://i.loli.net/2019/03/11/5c8663be34837.png",
    },
    {
      label: "直接访问",
      componentKey: 8,
      componentName: "text-text",
      api: "/report/getCountData",
      method: "get",
      dataKey: "countKey",
      col: 4.8,
      height: 100,
      previewImage: "https://i.loli.net/2019/03/11/5c8663be32edb.png",
    },
    {
      label: "搜索引擎",
      componentKey: 9,
      componentName: "text-text",
      api: "/report/getCountData",
      method: "get",
      dataKey: "countKey",
      col: 4.8,
      height: 100,
      previewImage: "https://i.loli.net/2019/03/11/5c8663be360b8.png",
    },
    {
      label: "占位",
      componentKey: 10,
      componentName: "chart-bar-stack",
      api: "/report/getRandomData",
      method: "get",
      dataKey: "",
      col: 6,
      height: 250,
      previewImage: "https://i.loli.net/2019/03/11/5c8664d167fb0.png",
    },
    {
      label: "分布图",
      componentKey: 11,
      componentName: "chart-pie",
      api: "/report/getRandomData",
      method: "get",
      dataKey: "",
      col: 8,
      height: 250,
      previewImage: "https://i.loli.net/2019/03/11/5c8664d441ebe.png",
    },
    {
      label: "时段分布图",
      componentKey: 12,
      componentName: "chart-bar-pie",
      api: "/report/getRandomData",
      method: "get",
      dataKey: "",
      col: 12,
      height: 250,
      previewImage: "https://i.loli.net/2019/03/11/5c8664d473804.png",
    },
    {
      label: "趋势图",
      componentKey: 13,
      componentName: "chart-line",
      api: "/report/getRandomData",
      method: "get",
      dataKey: "",
      col: 12,
      height: 250,
      previewImage: "https://i.loli.net/2019/03/11/5c8664d491680.png",
    },
    {
      label: "类型分布图",
      componentKey: 14,
      componentName: "group-table-pie",
      api: "/report/getRandomData",
      method: "get",
      dataKey: "",
      col: 16,
      height: 250,
      previewImage: "https://i.loli.net/2019/03/11/5c8664d4d8a55.png",
    },
    {
      label: "评分图",
      componentKey: 15,
      componentName: "chart-line-area",
      api: "/report/getRandomData",
      method: "get",
      dataKey: "",
      col: 24,
      height: 250,
      previewImage: "https://i.loli.net/2019/03/11/5c8664d70cb13.png",
    },
    {
      label: "日间评分",
      componentKey: 16,
      componentName: "text-three-line-text",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        unit: "分",
      },
      method: "post",
      dataKey: "data.base_param.day_score",
      col: 4,
      height: 100,
      previewImage: "https://i.loli.net/2019/05/10/5cd51dd3823ae.png",
    },
    {
      label: "夜间评分",
      componentKey: 17,
      componentName: "text-three-line-text",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        unit: "分",
      },
      method: "post",
      dataKey: "data.base_param.night_score",
      col: 4,
      height: 100,
      previewImage: "https://i.loli.net/2019/05/10/5cd51dd386873.png",
    },
    {
      label: "总时长",
      componentKey: 18,
      componentName: "text-three-line-text",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        unit: "h",
      },
      method: "post",
      dataKey: "data.base_param.total_hours",
      col: 4,
      height: 100,
      previewImage: "https://i.loli.net/2019/05/10/5cd51dd3849a5.png",
    },
    {
      label: "平均时长",
      componentKey: 19,
      componentName: "text-three-line-text",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        unit: "h/车",
      },
      method: "post",
      dataKey: "data.base_param.avg_hours",
      col: 4,
      height: 100,
      previewImage: "https://i.loli.net/2019/05/10/5cd51dd380000.png",
    },
    {
      label: "运营评分",
      componentKey: 20,
      componentName: "text-three-line-text",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        unit: "分",
      },
      method: "post",
      dataKey: "data.base_param.operate_score",
      col: 4,
      height: 100,
      previewImage: "https://i.loli.net/2019/05/10/5cd5175635c0d.png",
    },
    {
      label: "非运营评分",
      componentKey: 21,
      componentName: "text-three-line-text",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        unit: "分",
      },
      method: "post",
      dataKey: "data.base_param.unoperate_score",
      col: 4,
      height: 100,
      previewImage: "https://i.loli.net/2019/05/10/5cd51798aba81.png",
    },
    {
      label: "高速评分",
      componentKey: 22,
      componentName: "text-three-line-text",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        unit: "分",
      },
      method: "post",
      dataKey: "data.base_param.expressway_score",
      col: 4,
      height: 100,
      previewImage: "https://i.loli.net/2019/05/10/5cd517c9c461a.png",
    },
    {
      label: "非高速评分",
      componentKey: 23,
      componentName: "text-three-line-text",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        unit: "分",
      },
      method: "post",
      dataKey: "data.base_param.normalway_score",
      col: 4,
      height: 100,
      previewImage: "https://i.loli.net/2019/05/10/5cd517c9c9fe4.png",
    },
    {
      label: "总里程",
      componentKey: 24,
      componentName: "text-three-line-text",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        unit: "km",
      },
      method: "post",
      dataKey: "data.base_param.total_mile",
      col: 4,
      height: 100,
      previewImage: "https://i.loli.net/2019/05/10/5cd517c9c82d4.png",
    },
    {
      label: "平均里程",
      componentKey: 25,
      componentName: "text-three-line-text",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        unit: "km/车",
      },
      method: "post",
      dataKey: "data.base_param.avg_mile",
      col: 4,
      height: 100,
      previewImage: "https://i.loli.net/2019/05/10/5cd517c9c62a9.png",
    },
    {
      label: "总事件",
      componentKey: 26,
      componentName: "text-three-line-text",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        unit: "次",
      },
      method: "post",
      dataKey: "data.base_param.total_event",
      col: 4,
      height: 100,
      previewImage: "https://i.loli.net/2019/05/10/5cd518c3abed0.png",
    },
    {
      label: "平均事件",
      componentKey: 27,
      componentName: "text-three-line-text",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        unit: "次/车",
      },
      method: "post",
      dataKey: "data.base_param.avg_event",
      col: 4,
      height: 100,
      previewImage: "https://i.loli.net/2019/05/10/5cd518c3a7bda.png",
    },
    {
      label: "运营次数",
      componentKey: 28,
      componentName: "text-three-line-text",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        unit: "次",
      },
      method: "post",
      dataKey: "data.base_param.total_operate",
      col: 4,
      height: 100,
      previewImage: "https://i.loli.net/2019/05/10/5cd518c3a9b58.png",
    },
    {
      label: "平均运营次数",
      componentKey: 29,
      componentName: "text-three-line-text",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        unit: "次/车",
      },
      method: "post",
      dataKey: "data.base_param.avg_operate",
      col: 4,
      height: 100,
      previewImage: "https://i.loli.net/2019/05/10/5cd518c3abed0.png",
    },
    {
      label: "最高车速",
      componentKey: 30,
      componentName: "text-three-line-text",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        unit: "km/h",
      },
      method: "post",
      dataKey: "data.base_param.max_speed",
      col: 4,
      height: 100,
      previewImage: "https://i.loli.net/2019/05/10/5cd528455478c.png",
    },
    {
      label: "平均车速",
      componentKey: 31,
      componentName: "text-three-line-text",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        unit: "km/h",
      },
      method: "post",
      dataKey: "data.base_param.avg_speed",
      col: 4,
      height: 100,
      previewImage: "https://i.loli.net/2019/05/10/5cd5284556301.png",
    },
    {
      label: "安全评分",
      componentKey: 32,
      componentName: "other-circle-security-rate",
      api: "/report/getcustomccdeptreport",
      method: "post",
      dataKey: "data.base_param.safe_score",
      col: 8,
      height: 250,
      previewImage: "https://i.loli.net/2019/05/10/5cd528454141d.png",
    },
    {
      label: "table",
      componentKey: 33,
      componentName: "table-block",
      api: "/report/getcustomccdeptreport",
      method: "post",
      dataKey: "",
      col: 8,
      height: 250,
      previewImage: "https://i.loli.net/2019/03/11/5c8663be3a93d.png",
    },
    {
      label: "转向灯控制评分",
      componentKey: 34,
      componentName: "other-circle-icon",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        iconName: "iconzhuanxiangdeng",
        iconSize: 55,
      },
      method: "post",
      dataKey: "data.dimension_score.turn_ctrl",
      col: 4,
      height: 200,
      previewImage: "https://i.loli.net/2019/05/10/5cd51943551e5.png",
    },
    {
      label: "刹车控制评分",
      componentKey: 35,
      componentName: "other-circle-icon",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        iconName: "iconchache",
        iconSize: 45,
      },
      method: "post",
      dataKey: "data.dimension_score.break_ctrl",
      col: 4,
      height: 200,
      previewImage: "https://i.loli.net/2019/05/10/5cd51943559a5.png",
    },
    {
      label: "转弯评分",
      componentKey: 36,
      componentName: "other-circle-icon",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        iconName: "iconShape",
        iconSize: 30,
      },
      method: "post",
      dataKey: "data.dimension_score.cornering",
      col: 4,
      height: 200,
      previewImage: "https://i.loli.net/2019/05/10/5cd5194367823.png",
    },
    {
      label: "加速评分",
      componentKey: 37,
      componentName: "other-circle-icon",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        iconName: "iconjiasu",
        iconSize: 40,
      },
      method: "post",
      dataKey: "data.dimension_score.acc",
      col: 4,
      height: 200,
      previewImage: "https://i.loli.net/2019/05/10/5cd51943683c7.png",
    },
    {
      label: "减速评分",
      componentKey: 38,
      componentName: "other-circle-icon",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        iconName: "iconjijiansu",
        iconSize: 35,
      },
      method: "post",
      dataKey: "data.dimension_score.slow",
      col: 4,
      height: 200,
      previewImage: "https://i.loli.net/2019/05/10/5cd5194368a35.png",
    },
    {
      label: "速度评分",
      componentKey: 39,
      componentName: "other-circle-icon",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        iconText: "SLI",
        iconSize: 32,
      },
      method: "post",
      dataKey: "data.dimension_score.sli",
      col: 4,
      height: 200,
      previewImage: "https://i.loli.net/2019/05/10/5cd5194369044.png",
    },
    {
      label: "追尾碰撞评分",
      componentKey: 40,
      componentName: "other-circle-icon",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        haveBox: true,
        iconName: "iconche",
        iconSize: 25,
      },
      method: "post",
      dataKey: "data.dimension_score.fcw",
      col: 6,
      height: 200,
      previewImage: "https://i.loli.net/2019/05/10/5cd519b14126c.png",
    },
    {
      label: "车道保持评分",
      componentKey: 41,
      componentName: "other-circle-icon",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        haveBox: true,
        iconName: "icontubiaozhizuomoban",
        iconSize: 50,
      },
      method: "post",
      dataKey: "data.dimension_score.lane",
      col: 6,
      height: 200,
      previewImage: "https://i.loli.net/2019/05/10/5cd519b15f19d.png",
    },
    {
      label: "车距控制评分",
      componentKey: 42,
      componentName: "other-circle-icon",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        haveBox: true,
        iconName: "iconche1",
        iconSize: 40,
      },
      method: "post",
      dataKey: "data.dimension_score.hmw",
      col: 6,
      height: 200,
      previewImage: "https://i.loli.net/2019/05/10/5cd519b15e362.png",
    },
    {
      label: "行人和非机动碰撞评分",
      componentKey: 43,
      componentName: "other-circle-icon",
      api: "/report/getcustomccdeptreport",
      mixinData: {
        haveBox: true,
        iconName: "iconhangren_",
        iconSize: 35,
      },
      method: "post",
      dataKey: "data.dimension_score.pcw",
      col: 6,
      height: 200,
      previewImage: "https://i.loli.net/2019/05/10/5cd519b153466.png",
    },
    {
      label: "报警事件分布",
      componentKey: 44,
      componentName: "chart-alarm-event-distribution",
      api: "/report/getcustomccdeptreport",
      method: "post",
      dataKey: "data.event_info",
      col: 12,
      height: 250,
      previewImage: "https://i.loli.net/2019/05/10/5cd51a093a109.png",
    },
    {
      label: "事件处理报表",
      componentKey: 45,
      componentName: "chart-event-processing-report",
      api: "/report/getcustomccdeptreport",
      method: "post",
      dataKey: "data.event_info",
      col: 12,
      height: 250,
      previewImage: "https://i.loli.net/2019/05/10/5cd51a093c3c2.png",
    },
    {
      label: "报警事件时段分布",
      componentKey: 46,
      componentName: "chart-alarm-interval-distribution",
      api: "/report/getcustomccdeptreport",
      method: "post",
      dataKey: "data.event_hour_list",
      col: 24,
      height: 250,
      previewImage: "https://i.loli.net/2019/05/10/5cd51a2c38573.png",
    },
    {
      label: "车辆评分",
      componentKey: 47,
      componentName: "group-vehicle-score",
      api: "/report/getcustomccdeptreport",
      method: "post",
      dataKey: "data.vehicle_score",
      col: 24,
      height: 400,
      previewImage: "https://i.loli.net/2019/05/10/5cd51a2ce44f9.png",
    },
    {
      label: "驾驶评分",
      componentKey: 48,
      componentName: "chart-driving-score-line",
      api: "/report/getcustomccdeptreport",
      method: "post",
      dataKey: "data.drive_score_list",
      col: 24,
      height: 200,
      previewImage: "https://i.loli.net/2019/05/10/5cd51a2cf3c9d.png",
    },
    {
      label: "驾驶评分",
      componentKey: 49,
      componentName: "chart-driving-score-bar",
      api: "/report/getcustomccdeptreport",
      method: "post",
      dataKey: "data.drive_score_list",
      col: 24,
      height: 200,
      previewImage: "https://i.loli.net/2019/05/10/5cd51a2cd71f4.png",
    },
  ],
  {
    title: "new-report",
    reportUnionKey: "83502436-dba6-4628-b564-c6920e2c2f15",
    children: [
      {
        align: "flex-start",
        initHeight: 150,
        index: 1,
        children: [
          {
            col: 8,
            componentKey: 32,
            initCol: "8",
            title: "security-rate",
            label: "安全评分",
            componentName: "other-circle-security-rate",
            api: "/report/getcustomccdeptreport",
            method: "post",
            dataKey: "data.base_param.safe_score",
            height: 250,
            previewImage: "https://i.loli.net/2019/05/10/5cd528454141d.png",
            showChildrenControllerBar: false,
          },
          {
            col: 4,
            componentKey: 16,
            initCol: "4",
            title: "daytime-score",
            label: "日间评分",
            componentName: "text-three-line-text",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              unit: "分",
            },
            method: "post",
            dataKey: "data.base_param.day_score",
            height: 100,
            previewImage: "https://i.loli.net/2019/05/10/5cd51dd3823ae.png",
            showChildrenControllerBar: false,
          },
          {
            col: 4,
            componentKey: 17,
            initCol: "4",
            title: "night-score",
            label: "夜间评分",
            componentName: "text-three-line-text",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              unit: "分",
            },
            method: "post",
            dataKey: "data.base_param.night_score",
            height: 100,
            previewImage: "https://i.loli.net/2019/05/10/5cd51dd386873.png",
            showChildrenControllerBar: false,
          },
          {
            col: 4,
            componentKey: 20,
            initCol: "4",
            title: "operation-score",
            label: "运营评分",
            componentName: "text-three-line-text",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              unit: "分",
            },
            method: "post",
            dataKey: "data.base_param.operate_score",
            height: 100,
            previewImage: "https://i.loli.net/2019/05/10/5cd5175635c0d.png",
            showChildrenControllerBar: false,
          },
          {
            col: 4,
            componentKey: 21,
            initCol: "4",
            title: "not-operation-score",
            label: "非运营评分",
            componentName: "text-three-line-text",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              unit: "分",
            },
            method: "post",
            dataKey: "data.base_param.unoperate_score",
            height: 100,
            previewImage: "https://i.loli.net/2019/05/10/5cd51798aba81.png",
            showChildrenControllerBar: false,
          },
        ],
        showControllerBar: false,
      },
      {
        align: "flex-start",
        initHeight: 100,
        index: 2,
        children: [
          {
            col: 4,
            componentKey: 18,
            initCol: 4,
            title: "total-time",
            label: "总时长",
            componentName: "text-three-line-text",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              unit: "h",
            },
            method: "post",
            dataKey: "data.base_param.total_hours",
            height: 100,
            previewImage: "https://i.loli.net/2019/05/10/5cd51dd3849a5.png",
            showChildrenControllerBar: false,
          },
          {
            col: 4,
            componentKey: 19,
            initCol: 4,
            title: "average-time",
            label: "平均时长",
            componentName: "text-three-line-text",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              unit: "h/车",
            },
            method: "post",
            dataKey: "data.base_param.avg_hours",
            height: 100,
            previewImage: "https://i.loli.net/2019/05/10/5cd51dd380000.png",
            showChildrenControllerBar: false,
          },
          {
            col: 4,
            componentKey: 22,
            initCol: 4,
            title: "high-speed-score",
            label: "高速评分",
            componentName: "text-three-line-text",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              unit: "分",
            },
            method: "post",
            dataKey: "data.base_param.expressway_score",
            height: 100,
            previewImage: "https://i.loli.net/2019/05/10/5cd517c9c461a.png",
            showChildrenControllerBar: false,
          },
          {
            col: 4,
            componentKey: 23,
            initCol: 4,
            title: "not-high-speed-score",
            label: "非高速评分",
            componentName: "text-three-line-text",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              unit: "分",
            },
            method: "post",
            dataKey: "data.base_param.normalway_score",
            height: 100,
            previewImage: "https://i.loli.net/2019/05/10/5cd517c9c9fe4.png",
            showChildrenControllerBar: false,
          },
          {
            col: 4,
            componentKey: 24,
            initCol: 4,
            title: "total-distance",
            label: "总里程",
            componentName: "text-three-line-text",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              unit: "km",
            },
            method: "post",
            dataKey: "data.base_param.total_mile",
            height: 100,
            previewImage: "https://i.loli.net/2019/05/10/5cd517c9c82d4.png",
            showChildrenControllerBar: false,
          },
          {
            col: 4,
            componentKey: 25,
            initCol: 4,
            title: "average-distance",
            label: "平均里程",
            componentName: "text-three-line-text",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              unit: "km/车",
            },
            method: "post",
            dataKey: "data.base_param.avg_mile",
            height: 100,
            previewImage: "https://i.loli.net/2019/05/10/5cd517c9c62a9.png",
            showChildrenControllerBar: false,
          },
        ],
        showControllerBar: false,
      },
      {
        align: "flex-start",
        initHeight: 100,
        index: 3,
        children: [
          {
            col: 4,
            componentKey: 26,
            initCol: 4,
            title: "total-events",
            label: "总事件",
            componentName: "text-three-line-text",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              unit: "次",
            },
            method: "post",
            dataKey: "data.base_param.total_event",
            height: 100,
            previewImage: "https://i.loli.net/2019/05/10/5cd518c3abed0.png",
            showChildrenControllerBar: false,
          },
          {
            col: 4,
            componentKey: 27,
            initCol: 4,
            title: "average-events",
            label: "平均事件",
            componentName: "text-three-line-text",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              unit: "次/车",
            },
            method: "post",
            dataKey: "data.base_param.avg_event",
            height: 100,
            previewImage: "https://i.loli.net/2019/05/10/5cd518c3a7bda.png",
            showChildrenControllerBar: false,
          },
          {
            col: 4,
            componentKey: 28,
            initCol: 4,
            title: "operating-frequency",
            label: "运营次数",
            componentName: "text-three-line-text",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              unit: "次",
            },
            method: "post",
            dataKey: "data.base_param.total_operate",
            height: 100,
            previewImage: "https://i.loli.net/2019/05/10/5cd518c3a9b58.png",
            showChildrenControllerBar: false,
          },
          {
            col: 4,
            componentKey: 29,
            initCol: 4,
            title: "average-number-of-operations",
            label: "平均运营次数",
            componentName: "text-three-line-text",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              unit: "次/车",
            },
            method: "post",
            dataKey: "data.base_param.avg_operate",
            height: 100,
            previewImage: "http://chuantu.xyz/t6/702/1557974107x1709417317.png",
            showChildrenControllerBar: false,
          },
          {
            col: 4,
            componentKey: 30,
            initCol: 4,
            title: "maximum-speed",
            label: "最高车速",
            componentName: "text-three-line-text",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              unit: "km/h",
            },
            method: "post",
            dataKey: "data.base_param.max_speed",
            height: 100,
            previewImage: "https://i.loli.net/2019/05/10/5cd528455478c.png",
            showChildrenControllerBar: false,
          },
          {
            col: 4,
            componentKey: 31,
            initCol: 4,
            title: "average-velocity-speed",
            label: "平均车速",
            componentName: "text-three-line-text",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              unit: "km/h",
            },
            method: "post",
            dataKey: "data.base_param.avg_speed",
            height: 100,
            previewImage: "https://i.loli.net/2019/05/10/5cd5284556301.png",
            showChildrenControllerBar: false,
          },
        ],
        showControllerBar: false,
      },
      {
        title: "维度评分",
        align: "flex-start",
        initHeight: 220,
        index: 4,
        children: [
          {
            col: 4,
            componentKey: 34,
            initCol: 4,
            title: "turn-signal-control-score",
            label: "转向灯控制评分",
            componentName: "other-circle-icon",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              iconName: "iconzhuanxiangdeng",
              iconSize: 55,
            },
            method: "post",
            dataKey: "data.dimension_score.turn_ctrl",
            height: 200,
            previewImage: "https://i.loli.net/2019/05/10/5cd51943551e5.png",
            showChildrenControllerBar: false,
          },
          {
            col: 4,
            componentKey: 35,
            initCol: 4,
            title: "brake-control-score",
            label: "刹车控制评分",
            componentName: "other-circle-icon",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              iconName: "iconchache",
              iconSize: 45,
            },
            method: "post",
            dataKey: "data.dimension_score.break_ctrl",
            height: 200,
            previewImage: "https://i.loli.net/2019/05/10/5cd51943559a5.png",
            showChildrenControllerBar: false,
          },
          {
            col: 4,
            componentKey: 36,
            initCol: 4,
            title: "turning-score",
            label: "转弯评分",
            componentName: "other-circle-icon",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              iconName: "iconShape",
              iconSize: 30,
            },
            method: "post",
            dataKey: "data.dimension_score.cornering",
            height: 200,
            previewImage: "https://i.loli.net/2019/05/10/5cd5194367823.png",
            showChildrenControllerBar: false,
          },
          {
            col: 4,
            componentKey: 37,
            initCol: 4,
            title: "accelerate-the-score",
            label: "加速评分",
            componentName: "other-circle-icon",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              iconName: "iconjiasu",
              iconSize: 40,
            },
            method: "post",
            dataKey: "data.dimension_score.acc",
            height: 200,
            previewImage: "https://i.loli.net/2019/05/10/5cd51943683c7.png",
            showChildrenControllerBar: false,
          },
          {
            col: 4,
            componentKey: 38,
            initCol: 4,
            title: "deceleration-score",
            label: "减速评分",
            componentName: "other-circle-icon",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              iconName: "iconjijiansu",
              iconSize: 35,
            },
            method: "post",
            dataKey: "data.dimension_score.slow",
            height: 200,
            previewImage: "https://i.loli.net/2019/05/10/5cd5194368a35.png",
            showChildrenControllerBar: false,
          },
          {
            col: 4,
            componentKey: 39,
            initCol: 4,
            title: "speed-rating",
            label: "速度评分",
            componentName: "other-circle-icon",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              iconText: "SLI",
              iconSize: 32,
            },
            method: "post",
            dataKey: "data.dimension_score.sli",
            height: 200,
            previewImage: "https://i.loli.net/2019/05/10/5cd5194369044.png",
            showChildrenControllerBar: false,
          },
        ],
        showControllerBar: false,
      },
      {
        align: "flex-start",
        initHeight: 250,
        index: 5,
        children: [
          {
            col: 6,
            componentKey: 40,
            initCol: 6,
            title: "rear-end-collision-rating",
            label: "追尾碰撞评分",
            componentName: "other-circle-icon",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              haveBox: true,
              iconName: "iconche",
              iconSize: 25,
            },
            method: "post",
            dataKey: "data.dimension_score.fcw",
            height: 200,
            previewImage: "https://i.loli.net/2019/05/10/5cd519b14126c.png",
            showChildrenControllerBar: false,
          },
          {
            col: 6,
            componentKey: 41,
            initCol: 6,
            title: "lane-retention-score",
            label: "车道保持评分",
            componentName: "other-circle-icon",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              haveBox: true,
              iconName: "icontubiaozhizuomoban",
              iconSize: 50,
            },
            method: "post",
            dataKey: "data.dimension_score.lane",
            height: 200,
            previewImage: "https://i.loli.net/2019/05/10/5cd519b15f19d.png",
            showChildrenControllerBar: false,
          },
          {
            col: 6,
            componentKey: 42,
            initCol: 6,
            title: "distance-control-rating",
            label: "车距控制评分",
            componentName: "other-circle-icon",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              haveBox: true,
              iconName: "iconche1",
              iconSize: 40,
            },
            method: "post",
            dataKey: "data.dimension_score.hmw",
            height: 200,
            previewImage: "https://i.loli.net/2019/05/10/5cd519b15e362.png",
            showChildrenControllerBar: false,
          },
          {
            col: 6,
            componentKey: 43,
            initCol: 6,
            title: "pedestrian-and-non-motor-vehicle-collision-rating",
            label: "行人和非机动碰撞评分",
            componentName: "other-circle-icon",
            api: "/report/getcustomccdeptreport",
            mixinData: {
              haveBox: true,
              iconName: "iconhangren_",
              iconSize: 35,
            },
            method: "post",
            dataKey: "data.dimension_score.pcw",
            height: 200,
            previewImage: "https://i.loli.net/2019/05/10/5cd519b153466.png",
            showChildrenControllerBar: false,
          },
        ],
        showControllerBar: false,
      },
      {
        title: "报警事件",
        align: "flex-start",
        initHeight: 250,
        index: 6,
        children: [
          {
            col: 12,
            componentKey: 44,
            initCol: 12,
            title: "alarm-event-distribution",
            label: "报警事件分布",
            componentName: "chart-alarm-event-distribution",
            api: "/report/getcustomccdeptreport",
            method: "post",
            dataKey: "data.event_info",
            height: 250,
            previewImage: "https://i.loli.net/2019/05/10/5cd51a093a109.png",
            showChildrenControllerBar: false,
          },
          {
            col: 12,
            componentKey: 45,
            initCol: 12,
            title: "event-processing-report",
            label: "事件处理报表",
            componentName: "chart-event-processing-report",
            api: "/report/getcustomccdeptreport",
            method: "post",
            dataKey: "data.event_info",
            height: 250,
            previewImage: "https://i.loli.net/2019/05/10/5cd51a093c3c2.png",
            showChildrenControllerBar: false,
          },
        ],
        showControllerBar: false,
      },
      {
        title: "报警事件时段分布",
        align: "flex-start",
        initHeight: 250,
        index: 7,
        children: [
          {
            col: 24,
            componentKey: 46,
            initCol: 24,
            title: "alarm-interval-distribution",
            label: "报警事件时段分布",
            componentName: "chart-alarm-interval-distribution",
            api: "/report/getcustomccdeptreport",
            method: "post",
            dataKey: "data.event_hour_list",
            height: 250,
            previewImage: "https://i.loli.net/2019/05/10/5cd51a2c38573.png",
            showChildrenControllerBar: false,
          },
        ],
        showControllerBar: false,
      },
      {
        title: "车辆评分",
        align: "flex-start",
        initHeight: 400,
        index: 8,
        children: [
          {
            col: 24,
            componentKey: 47,
            initCol: 24,
            title: "vehicle-score",
            label: "车辆评分",
            componentName: "group-vehicle-score",
            api: "/report/getcustomccdeptreport",
            method: "post",
            dataKey: "data.vehicle_score",
            height: 400,
            previewImage: "https://i.loli.net/2019/05/10/5cd51a2ce44f9.png",
            showChildrenControllerBar: false,
          },
        ],
        showControllerBar: false,
      },
      {
        title: "驾驶评分",
        align: "flex-start",
        initHeight: 250,
        index: 9,
        children: [
          {
            col: 24,
            componentKey: 48,
            initCol: 24,
            title: "driving-score-line",
            label: "驾驶评分",
            componentName: "chart-driving-score-line",
            api: "/report/getcustomccdeptreport",
            method: "post",
            dataKey: "data.drive_score_list",
            height: 200,
            previewImage: "https://i.loli.net/2019/05/10/5cd51a2cf3c9d.png",
            showChildrenControllerBar: false,
          },
        ],
        showControllerBar: false,
      },
      {
        align: "flex-start",
        initHeight: 250,
        index: 10,
        children: [
          {
            col: 24,
            componentKey: 49,
            initCol: 24,
            title: "driving-score-bar",
            label: "驾驶评分",
            componentName: "chart-driving-score-bar",
            api: "/report/getcustomccdeptreport",
            method: "post",
            dataKey: "data.drive_score_list",
            height: 200,
            previewImage: "https://i.loli.net/2019/05/10/5cd51a2cd71f4.png",
            showChildrenControllerBar: false,
          },
        ],
        showControllerBar: false,
      },
    ],
  },
];

export const noData = [
  [],
  {
    title: '',
    reportUnionKey: '',
    children: [
      {
        align: "flex-start",
        initHeight: 150,
        index: 1,
        children: [
          {
            col: 8,
            componentKey: 32,
            initCol: "24",
            title: "security-rate",
            label: "安全评分",
            componentName: "other-circle-security-rate",
            api: "/report/getcustomccdeptreport",
            method: "post",
            dataKey: "data.base_param.safe_score",
            height: 250,
            previewImage: "https://i.loli.net/2019/05/10/5cd528454141d.png",
            showChildrenControllerBar: false,
          },
          // {
          //   col: 4,
          //   componentKey: 16,
          //   initCol: "4",
          //   title: "daytime-score",
          //   label: "日间评分",
          //   componentName: "text-three-line-text",
          //   api: "/report/getcustomccdeptreport",
          //   mixinData: {
          //     unit: "分",
          //   },
          //   method: "post",
          //   dataKey: "data.base_param.day_score",
          //   height: 100,
          //   previewImage: "https://i.loli.net/2019/05/10/5cd51dd3823ae.png",
          //   showChildrenControllerBar: false,
          // },
          // {
          //   col: 4,
          //   componentKey: 17,
          //   initCol: "4",
          //   title: "night-score",
          //   label: "夜间评分",
          //   componentName: "text-three-line-text",
          //   api: "/report/getcustomccdeptreport",
          //   mixinData: {
          //     unit: "分",
          //   },
          //   method: "post",
          //   dataKey: "data.base_param.night_score",
          //   height: 100,
          //   previewImage: "https://i.loli.net/2019/05/10/5cd51dd386873.png",
          //   showChildrenControllerBar: false,
          // },
          // {
          //   col: 4,
          //   componentKey: 20,
          //   initCol: "4",
          //   title: "operation-score",
          //   label: "运营评分",
          //   componentName: "text-three-line-text",
          //   api: "/report/getcustomccdeptreport",
          //   mixinData: {
          //     unit: "分",
          //   },
          //   method: "post",
          //   dataKey: "data.base_param.operate_score",
          //   height: 100,
          //   previewImage: "https://i.loli.net/2019/05/10/5cd5175635c0d.png",
          //   showChildrenControllerBar: false,
          // },
          // {
          //   col: 4,
          //   componentKey: 21,
          //   initCol: "4",
          //   title: "not-operation-score",
          //   label: "非运营评分",
          //   componentName: "text-three-line-text",
          //   api: "/report/getcustomccdeptreport",
          //   mixinData: {
          //     unit: "分",
          //   },
          //   method: "post",
          //   dataKey: "data.base_param.unoperate_score",
          //   height: 100,
          //   previewImage: "https://i.loli.net/2019/05/10/5cd51798aba81.png",
          //   showChildrenControllerBar: false,
          // },
        ],
        showControllerBar: false,
      },
    ]
  }
]
