export const rightData = [
  {
    label: "占位",
    componentKey: 1,
    componentName: "other-block",
    api: "",
    method: "get",
    dataKey: "",
    col: 1,
    height: 250,
    previewImage: "https://i.loli.net/2019/03/11/5c8663be38f28.png",
  },
  {
    label: "占位",
    componentKey: 2,
    componentName: "other-block",
    api: "",
    method: "get",
    dataKey: "",
    col: 2,
    height: 250,
    previewImage: "https://i.loli.net/2019/03/11/5c8663be37781.png",
  },
  {
    label: "占位",
    componentKey: 3,
    componentName: "other-block",
    api: "",
    method: "get",
    dataKey: "",
    col: 3,
    height: 250,
    previewImage: "https://i.loli.net/2019/03/11/5c8663be3c255.png",
  },
  {
    label: "占位",
    componentKey: 4,
    componentName: "other-block",
    api: "",
    method: "get",
    dataKey: "",
    col: 4,
    height: 250,
    previewImage: "https://i.loli.net/2019/03/11/5c8664d04e3e7.png",
  },
  {
    label: "邮件营销",
    componentKey: 5,
    componentName: "text-text",
    api: "/report/getCountData",
    method: "get",
    dataKey: "countKey",
    col: 4.8,
    height: 100,
    previewImage: "https://i.loli.net/2019/03/11/5c8663be3a93d.png",
  },
  {
    label: "联盟广告",
    componentKey: 6,
    componentName: "text-text",
    api: "/report/getCountData",
    method: "get",
    dataKey: "countKey",
    col: 4.8,
    height: 100,
    previewImage: "https://i.loli.net/2019/03/11/5c8663be31676.png",
  },
  {
    label: "视频广告",
    componentKey: 7,
    componentName: "text-text",
    api: "/report/getCountData",
    method: "get",
    dataKey: "countKey",
    col: 4.8,
    height: 100,
    previewImage: "https://i.loli.net/2019/03/11/5c8663be34837.png",
  },
  {
    label: "直接访问",
    componentKey: 8,
    componentName: "text-text",
    api: "/report/getCountData",
    method: "get",
    dataKey: "countKey",
    col: 4.8,
    height: 100,
    previewImage: "https://i.loli.net/2019/03/11/5c8663be32edb.png",
  },
  {
    label: "搜索引擎",
    componentKey: 9,
    componentName: "text-text",
    api: "/report/getCountData",
    method: "get",
    dataKey: "countKey",
    col: 4.8,
    height: 100,
    previewImage: "https://i.loli.net/2019/03/11/5c8663be360b8.png",
  },
  {
    label: "占位",
    componentKey: 10,
    componentName: "chart-bar-stack",
    api: "/report/getRandomData",
    method: "get",
    dataKey: "",
    col: 6,
    height: 250,
    previewImage: "https://i.loli.net/2019/03/11/5c8664d167fb0.png",
  },
  {
    label: "分布图",
    componentKey: 11,
    componentName: "chart-pie",
    api: "/report/getRandomData",
    method: "get",
    dataKey: "",
    col: 8,
    height: 250,
    previewImage: "https://i.loli.net/2019/03/11/5c8664d441ebe.png",
  },
  {
    label: "时段分布图",
    componentKey: 12,
    componentName: "chart-bar-pie",
    api: "/report/getRandomData",
    method: "get",
    dataKey: "",
    col: 12,
    height: 250,
    previewImage: "https://i.loli.net/2019/03/11/5c8664d473804.png",
  },
  {
    label: "趋势图",
    componentKey: 13,
    componentName: "chart-line",
    api: "/report/getRandomData",
    method: "get",
    dataKey: "",
    col: 12,
    height: 250,
    previewImage: "https://i.loli.net/2019/03/11/5c8664d491680.png",
  },
  {
    label: "类型分布图",
    componentKey: 14,
    componentName: "group-table-pie",
    api: "/report/getRandomData",
    method: "get",
    dataKey: "",
    col: 16,
    height: 250,
    previewImage: "https://i.loli.net/2019/03/11/5c8664d4d8a55.png",
  },
  {
    label: "评分图",
    componentKey: 15,
    componentName: "chart-line-area",
    api: "/report/getRandomData",
    method: "get",
    dataKey: "",
    col: 24,
    height: 250,
    previewImage: "https://i.loli.net/2019/03/11/5c8664d70cb13.png",
  },
  {
    label: "日间评分",
    componentKey: 16,
    componentName: "text-three-line-text",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      unit: "分",
    },
    method: "post",
    dataKey: "data.base_param.day_score",
    col: 4,
    height: 100,
    previewImage: "https://i.loli.net/2019/05/10/5cd51dd3823ae.png",
  },
  {
    label: "夜间评分",
    componentKey: 17,
    componentName: "text-three-line-text",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      unit: "分",
    },
    method: "post",
    dataKey: "data.base_param.night_score",
    col: 4,
    height: 100,
    previewImage: "https://i.loli.net/2019/05/10/5cd51dd386873.png",
  },
  {
    label: "总时长",
    componentKey: 18,
    componentName: "text-three-line-text",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      unit: "h",
    },
    method: "post",
    dataKey: "data.base_param.total_hours",
    col: 4,
    height: 100,
    previewImage: "https://i.loli.net/2019/05/10/5cd51dd3849a5.png",
  },
  {
    label: "平均时长",
    componentKey: 19,
    componentName: "text-three-line-text",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      unit: "h/车",
    },
    method: "post",
    dataKey: "data.base_param.avg_hours",
    col: 4,
    height: 100,
    previewImage: "https://i.loli.net/2019/05/10/5cd51dd380000.png",
  },
  {
    label: "运营评分",
    componentKey: 20,
    componentName: "text-three-line-text",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      unit: "分",
    },
    method: "post",
    dataKey: "data.base_param.operate_score",
    col: 4,
    height: 100,
    previewImage: "https://i.loli.net/2019/05/10/5cd5175635c0d.png",
  },
  {
    label: "非运营评分",
    componentKey: 21,
    componentName: "text-three-line-text",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      unit: "分",
    },
    method: "post",
    dataKey: "data.base_param.unoperate_score",
    col: 4,
    height: 100,
    previewImage: "https://i.loli.net/2019/05/10/5cd51798aba81.png",
  },
  {
    label: "高速评分",
    componentKey: 22,
    componentName: "text-three-line-text",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      unit: "分",
    },
    method: "post",
    dataKey: "data.base_param.expressway_score",
    col: 4,
    height: 100,
    previewImage: "https://i.loli.net/2019/05/10/5cd517c9c461a.png",
  },
  {
    label: "非高速评分",
    componentKey: 23,
    componentName: "text-three-line-text",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      unit: "分",
    },
    method: "post",
    dataKey: "data.base_param.normalway_score",
    col: 4,
    height: 100,
    previewImage: "https://i.loli.net/2019/05/10/5cd517c9c9fe4.png",
  },
  {
    label: "总里程",
    componentKey: 24,
    componentName: "text-three-line-text",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      unit: "km",
    },
    method: "post",
    dataKey: "data.base_param.total_mile",
    col: 4,
    height: 100,
    previewImage: "https://i.loli.net/2019/05/10/5cd517c9c82d4.png",
  },
  {
    label: "平均里程",
    componentKey: 25,
    componentName: "text-three-line-text",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      unit: "km/车",
    },
    method: "post",
    dataKey: "data.base_param.avg_mile",
    col: 4,
    height: 100,
    previewImage: "https://i.loli.net/2019/05/10/5cd517c9c62a9.png",
  },
  {
    label: "总事件",
    componentKey: 26,
    componentName: "text-three-line-text",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      unit: "次",
    },
    method: "post",
    dataKey: "data.base_param.total_event",
    col: 4,
    height: 100,
    previewImage: "https://i.loli.net/2019/05/10/5cd518c3abed0.png",
  },
  {
    label: "平均事件",
    componentKey: 27,
    componentName: "text-three-line-text",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      unit: "次/车",
    },
    method: "post",
    dataKey: "data.base_param.avg_event",
    col: 4,
    height: 100,
    previewImage: "https://i.loli.net/2019/05/10/5cd518c3a7bda.png",
  },
  {
    label: "运营次数",
    componentKey: 28,
    componentName: "text-three-line-text",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      unit: "次",
    },
    method: "post",
    dataKey: "data.base_param.total_operate",
    col: 4,
    height: 100,
    previewImage: "https://i.loli.net/2019/05/10/5cd518c3a9b58.png",
  },
  {
    label: "平均运营次数",
    componentKey: 29,
    componentName: "text-three-line-text",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      unit: "次/车",
    },
    method: "post",
    dataKey: "data.base_param.avg_operate",
    col: 4,
    height: 100,
    previewImage: "https://i.loli.net/2019/05/10/5cd518c3a9b58.png",
  },
  {
    label: "最高车速",
    componentKey: 30,
    componentName: "text-three-line-text",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      unit: "km/h",
    },
    method: "post",
    dataKey: "data.base_param.max_speed",
    col: 4,
    height: 100,
    previewImage: "https://i.loli.net/2019/05/10/5cd528455478c.png",
  },
  {
    label: "平均车速",
    componentKey: 31,
    componentName: "text-three-line-text",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      unit: "km/h",
    },
    method: "post",
    dataKey: "data.base_param.avg_speed",
    col: 4,
    height: 100,
    previewImage: "https://i.loli.net/2019/05/10/5cd5284556301.png",
  },
  {
    label: "安全评分",
    componentKey: 32,
    componentName: "other-circle-security-rate",
    api: "/report/getcustomccdeptreport",
    method: "post",
    dataKey: "data.base_param.safe_score",
    col: 8,
    height: 250,
    previewImage: "https://i.loli.net/2019/05/10/5cd528454141d.png",
  },
  {
    label: "table",
    componentKey: 33,
    componentName: "table-block",
    api: "/report/getcustomccdeptreport",
    method: "post",
    dataKey: "",
    col: 8,
    height: 250,
    previewImage: "https://i.loli.net/2019/03/11/5c8663be3a93d.png",
  },
  {
    label: "转向灯控制评分",
    componentKey: 34,
    componentName: "other-circle-icon",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      iconName: "iconzhuanxiangdeng",
      iconSize: 55,
    },
    method: "post",
    dataKey: "data.dimension_score.turn_ctrl",
    col: 4,
    height: 200,
    previewImage: "https://i.loli.net/2019/05/10/5cd51943551e5.png",
  },
  {
    label: "刹车控制评分",
    componentKey: 35,
    componentName: "other-circle-icon",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      iconName: "iconchache",
      iconSize: 45,
    },
    method: "post",
    dataKey: "data.dimension_score.break_ctrl",
    col: 4,
    height: 200,
    previewImage: "https://i.loli.net/2019/05/10/5cd51943559a5.png",
  },
  {
    label: "转弯评分",
    componentKey: 36,
    componentName: "other-circle-icon",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      iconName: "iconShape",
      iconSize: 30,
    },
    method: "post",
    dataKey: "data.dimension_score.cornering",
    col: 4,
    height: 200,
    previewImage: "https://i.loli.net/2019/05/10/5cd5194367823.png",
  },
  {
    label: "加速评分",
    componentKey: 37,
    componentName: "other-circle-icon",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      iconName: "iconjiasu",
      iconSize: 40,
    },
    method: "post",
    dataKey: "data.dimension_score.acc",
    col: 4,
    height: 200,
    previewImage: "https://i.loli.net/2019/05/10/5cd51943683c7.png",
  },
  {
    label: "减速评分",
    componentKey: 38,
    componentName: "other-circle-icon",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      iconName: "iconjijiansu",
      iconSize: 35,
    },
    method: "post",
    dataKey: "data.dimension_score.slow",
    col: 4,
    height: 200,
    previewImage: "https://i.loli.net/2019/05/10/5cd5194368a35.png",
  },
  {
    label: "速度评分",
    componentKey: 39,
    componentName: "other-circle-icon",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      iconText: "SLI",
      iconSize: 32,
    },
    method: "post",
    dataKey: "data.dimension_score.sli",
    col: 4,
    height: 200,
    previewImage: "https://i.loli.net/2019/05/10/5cd5194369044.png",
  },
  {
    label: "追尾碰撞评分",
    componentKey: 40,
    componentName: "other-circle-icon",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      haveBox: true,
      iconName: "iconche",
      iconSize: 25,
    },
    method: "post",
    dataKey: "data.dimension_score.fcw",
    col: 6,
    height: 200,
    previewImage: "https://i.loli.net/2019/05/10/5cd519b14126c.png",
  },
  {
    label: "车道保持评分",
    componentKey: 41,
    componentName: "other-circle-icon",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      haveBox: true,
      iconName: "icontubiaozhizuomoban",
      iconSize: 50,
    },
    method: "post",
    dataKey: "data.dimension_score.lane",
    col: 6,
    height: 200,
    previewImage: "https://i.loli.net/2019/05/10/5cd519b15f19d.png",
  },
  {
    label: "车距控制评分",
    componentKey: 42,
    componentName: "other-circle-icon",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      haveBox: true,
      iconName: "iconche1",
      iconSize: 40,
    },
    method: "post",
    dataKey: "data.dimension_score.hmw",
    col: 6,
    height: 200,
    previewImage: "https://i.loli.net/2019/05/10/5cd519b15e362.png",
  },
  {
    label: "行人和非机动碰撞评分",
    componentKey: 43,
    componentName: "other-circle-icon",
    api: "/report/getcustomccdeptreport",
    mixinData: {
      haveBox: true,
      iconName: "iconhangren_",
      iconSize: 35,
    },
    method: "post",
    dataKey: "data.dimension_score.pcw",
    col: 6,
    height: 200,
    previewImage: "https://i.loli.net/2019/05/10/5cd519b153466.png",
  },
  {
    label: "报警事件分布",
    componentKey: 44,
    componentName: "chart-alarm-event-distribution",
    api: "/report/getcustomccdeptreport",
    method: "post",
    dataKey: "data.event_info",
    col: 12,
    height: 250,
    previewImage: "https://i.loli.net/2019/05/10/5cd51a093a109.png",
  },
  {
    label: "事件处理报表",
    componentKey: 45,
    componentName: "chart-event-processing-report",
    api: "/report/getcustomccdeptreport",
    method: "post",
    dataKey: "data.event_info",
    col: 12,
    height: 250,
    previewImage: "https://i.loli.net/2019/05/10/5cd51a093c3c2.png",
  },
  {
    label: "报警事件时段分布",
    componentKey: 46,
    componentName: "chart-alarm-interval-distribution",
    api: "/report/getcustomccdeptreport",
    method: "post",
    dataKey: "data.event_hour_list",
    col: 24,
    height: 250,
    previewImage: "https://i.loli.net/2019/05/10/5cd51a2c38573.png",
  },
  {
    label: "车辆评分",
    componentKey: 47,
    componentName: "group-vehicle-score",
    api: "/report/getcustomccdeptreport",
    method: "post",
    dataKey: "data.vehicle_score",
    col: 24,
    height: 400,
    previewImage: "https://i.loli.net/2019/05/10/5cd51a2ce44f9.png",
  },
  {
    label: "驾驶评分",
    componentKey: 48,
    componentName: "chart-driving-score-line",
    api: "/report/getcustomccdeptreport",
    method: "post",
    dataKey: "data.drive_score_list",
    col: 24,
    height: 200,
    previewImage: "https://i.loli.net/2019/05/10/5cd51a2cf3c9d.png",
  },
  {
    label: "驾驶评分",
    componentKey: 49,
    componentName: "chart-driving-score-bar",
    api: "/report/getcustomccdeptreport",
    method: "post",
    dataKey: "data.drive_score_list",
    col: 24,
    height: 200,
    previewImage: "https://i.loli.net/2019/05/10/5cd51a2cd71f4.png",
  },
];
